spring:
  application:
    name: service-mesh2
server:
  port: 8081
  servlet:
    context-path: /service-mesh2
logging:
  level:
    org.springframework: debug
    org.springframework.web: info
    tomcat: info

